### ISSUE TITLE
clarify documentation

### ISSUE THREAD

**Issue by mvolkmann** [jdsteinbach/eleventy-plugin-toc#16]
I misunderstood the step "4. Use the filter in your template".
After a while I figured out that that HTML goes in a layout, not in a markdown file.
Maybe it would be more clear to say "4. Use the filter in your layout".

**Comment by helmutgranda** [comment]
I agree! we have TOCs by MD file, not a big deal we can make it global but at first I thought it was a mistake somewhere else.

**Comment by jdsteinbach** [comment]
Thanks for the clarification! Since Eleventy only provides the `content` variable in layout templates, I'll clarify that the filter needs to go there, not in a content file.
