### ISSUE TITLE
Nested list is rendered as ol with "ul" option set to true

### ISSUE THREAD

**Issue by darekkay** [jdsteinbach/eleventy-plugin-toc#19]
When using `{ ul: true }`, the first level list is being correctly rendered as `<ul>`. However, the nested lists are still using an `<ol>`:

![image](https://user-images.githubusercontent.com/3101914/97806670-2ac4aa00-1c5d-11eb-9c6a-63be75198b0c.png)

Is this an expected behavior?

**Comment by jdsteinbach** [comment]
@darekkay This should be fixed now: `ul` / `ol` will be nested correctly.
@MichaelSolati Thanks for the PR!
